### ISSUE TITLE
got a problem

### ISSUE THREAD

**Issue by FireJohnny** [dougalsutherland/vlfeat-ctypes#6]
when i use import vlfeat
use vlfeat.dsift(img)
i get a problem  : AttributeError: 'Image' object has no attribute 'dtype' form
Traceback (most recent call last):
  File "C:/Users/FireJohnny/Desktop/PHOW/sift.py", line 11, in <module>
    f = vlfeat.vl_dsift(img)
  File "C:\Python27\lib\site-packages\vlfeat\__init__.py", line 13, in vl_dsift
    return f(*args, **kwargs)
  File "C:\Python27\lib\site-packages\vlfeat\dsift.py", line 121, in vl_dsift
    data = as_float_image(data, dtype=np.float32, order=order)
  File "C:\Python27\lib\site-packages\vlfeat\utils.py", line 10, in as_float_image
    if image.dtype.kind in ('u', 'i'):
AttributeError: 'Image' object has no attribute 'dtype'

how i  can fix it

**Comment by djsutherland** [comment]
Should be fixed by 6bf0b8b70938d2f85376c864c44af66dee56c677, in the new 0.1.5 release; pip update and try again.

**Comment by FireJohnny** [comment]
thanks
